repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.191'
    hooks:
      - id: ruff
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        files: ^(src/|tests/)
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        exclude: '.*/migrations/.*'
        args: [
            '--profile=black',
            '--line-length=88',
            # '--multi-line=3',
            '--force-single-line-imports',
            '--force-grid-wrap=0',
            '--trailing-comma',
            '--use-parentheses',
            '--ensure-newline-before-comments',
            '--filter-files',
        ]
      - id: wily
        name: wily
        entry: wily diff
        verbose: true
        language: python
        additional_dependencies: [wily]
